INSERT INTO Provincia (Nome, IDRegione) VALUES
(L'Aquila', 1),
('Teramo', 1),
('Pescara', 1),
('Chieti', 1),
('Potenza', 2),
('Matera', 2),
('Catanzaro', 3),
('Cosenza', 3),
('Crotone', 3),
('Reggio Calabria', 3),
('Vibo Valentia', 3),
('Avellino', 4),
('Benevento', 4),
('Caserta', 4),
('Napoli', 4),
('Salerno', 4),
('Bologna', 5),
('Ferrara', 5),
('Forlì-Cesena', 5),
('Modena', 5),
('Parma', 5),
('Piacenza', 5),
('Ravenna', 5),
('Reggio Emilia', 5),
('Rimini', 5),
('Gorizia', 6),
('Pordenone', 6),
('Trieste', 6),
('Udine', 6),
('Frosinone', 7),
('Latina', 7),
('Rieti', 7),
('Roma', 7),
('Viterbo', 7),
('Genova', 8),
('Imperia', 8),
('La Spezia', 8),
('Savona', 8),
('Bergamo', 9),
('Brescia', 9),
('Como', 9),
('Cremona', 9),
('Lecco', 9),
('Lodi', 9),
('Mantova', 9),
('Milano', 9),
('Monza e Brianza', 9),
('Pavia', 9),
('Sondrio', 9),
('Varese', 9),
('Ancona', 10),
('Ascoli Piceno', 10),
('Fermo', 10),
('Macerata', 10),
('Pesaro e Urbino', 10),
('Campobasso', 11),
('Isernia', 11),
('Alessandria', 12),
('Asti', 12),
('Biella', 12),
('Cuneo', 12),
('Novara', 12),
('Torino', 12),
('Verbano-Cusio-Ossola', 12),
('Vercelli', 12),
('Bari', 13),
('Barletta-Andria-Trani', 13),
('Brindisi', 13),
('Foggia', 13),
('Lecce', 13),
('Taranto', 13),
('Cagliari', 14),
('Nuoro', 14),
('Oristano', 14),
('Sassari', 14),
('Sud Sardegna', 14),
('Agrigento', 15),
('Caltanissetta', 15),
('Catania', 15),
('Enna', 15),
('Messina', 15),
('Palermo', 15),
('Ragusa', 15),
('Siracusa', 15),
('Trapani', 15),
('Arezzo', 16),
('Firenze', 16),
('Grosseto', 16),
('Livorno', 16),
('Lucca', 16),
('Massa-Carrara', 16),
('Pisa', 16),
('Pistoia', 16),
('Prato', 16),
('Siena', 16),
('Bolzano', 17),
('Trento', 17),
('Perugia', 18),
('Terni', 18),
('Aosta', 19),
('Belluno', 20),
('Padova', 20),
('Rovigo', 20),
('Treviso', 20),
('Venezia', 20),
('Verona', 20),
('Vicenza', 20),
('Monza e Brianza', 9),
('Barletta-Andria-Trani', 13),
('Sud Sardegna', 14);